### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by Emily-Jiang** [Azure-Samples/open-liberty-on-aro#3]
1. Add link to [MicroProfile] (https://microprofile.io/) 
2. Add link to [Jakarta EE] (https://jakarta.ee/)
3.  In the last statement, it might be helpful to put a screen shot on how to find host and port;

> Once the Open Liberty application is up and running, open HOST/PORT of the route in your browser to visit the application home page.

**Comment by majguo** [comment]
Hi @Emily-Jiang , I've opened a PR to address the 1st two comments. 
Regarding to the 3rd comment, actually there is a sample output of `oc get route` to get **HOST/PORT** ahead of this statement in the [guide for review](https://github.com/edburns/azure-docs/blob/jiangma-aro-openliberty-howto-public/articles/openshift/howto-deploy-java-openliberty-app.md):
```bash
# Check if route is created by Operator
oc get route

NAME                 HOST/PORT                                                                PATH   SERVICES             PORT       TERMINATION   WILDCARD
javaee-cafe-simple   javaee-cafe-simple-open-liberty-demo.apps.aqlm62xm.rnfghf.aroapp.io             javaee-cafe-simple   9080-tcp                 None
```
So I think user can follow this to find out **HOST/PORT**, what do you think?

**Comment by majguo** [comment]
Hi @Emily-Jiang,  
The relative PR is merged. Feel free close the issue if you're OK with the changes or leave other comments if any.
