### ISSUE TITLE
Use images from icr.io/appcafe

### ISSUE THREAD

**Issue by gcharters** [Azure-Samples/open-liberty-on-aro#30]
The best source of images for Liberty is the IBM Container Registry - `icr.io/appcafe`. These images are built, scanned and certified by the Liberty team and are available unauthenticated and without rate limits.  We should update the Dockerfiles to use these images.  It should just be a case of prefixing the `FROM` lines with `icr.io/appcafe`.

**Comment by majguo** [comment]
It's fixed by #49.
